DEFINE tab_space_table=ACT0_TAB
DEFINE tab_space_index=ACT0_IDX

PROMPT Creating TABLE nuclide_tracer_type
CREATE TABLE nuclide_tracer_type (
	tracer_type_id		NUMBER(8,0)		NOT NULL
		CONSTRAINT pk_tracer_type
		PRIMARY KEY
		USING INDEX TABLESPACE &tab_space_index
		STORAGE (INITIAL 10k),
    tracer_type_name			VARCHAR2(16)		NOT NULL
	)
	TABLESPACE &TAB_SPACE_TABLE
	STORAGE (INITIAL 10k);
	
CREATE SEQUENCE nuclide_tracer_type_seq_id MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
grant select on nuclide_tracer_type_seq_id to osiris_writer;

Insert into OSIRIS.NUCLIDE_TRACER_TYPE (tracer_type_id,tracer_type_name) values (nuclide_tracer_type_seq_id.nextval, 'mother');
Insert into OSIRIS.NUCLIDE_TRACER_TYPE (tracer_type_id,tracer_type_name) values (nuclide_tracer_type_seq_id.nextval, 'daughter');
Insert into OSIRIS.NUCLIDE_TRACER_TYPE (tracer_type_id,tracer_type_name) values (nuclide_tracer_type_seq_id.nextval, 'in-vivo');
Insert into OSIRIS.NUCLIDE_TRACER_TYPE (tracer_type_id,tracer_type_name) values (nuclide_tracer_type_seq_id.nextval, 'external');

alter table nuclide_bottle add tracer_type_id number(8,0) constraint fk_tracer_type REFERENCES nuclide_tracer_type(tracer_type_id);
alter table nuclide_bottle_aud add tracer_type_id number(8,0);

update nuclide_bottle set tracer_type_id = 3 where BATCH_NAME like 'In-Vivo-Sample%';
--update nuclide_bottle set tracer_type_id = 2 where nuclide_bottle_id in (select distinct(new_nuclide_bottle_id) from nuclide_usage where assay_type like '%New Tracer Creation%');
update nuclide_bottle set tracer_type_id = 2 where nuclide_bottle_id in (select distinct(new_nuclide_bottle_id) from nuclide_usage where assay_type not like 'In-Vivo Experiment');
update nuclide_bottle set tracer_type_id = 1 where nuclide_bottle_id in (select distinct(nuclide_bottle_id) from nuclide_usage where new_nuclide_bottle_id is null);
--no usage done for the rest of parent tracers (select nuclide_bottle_id from nuclide_bottle where tracer_type_id is null)
update nuclide_bottle set tracer_type_id = 1 where tracer_type_id is null;

alter table nuclide_usage_aud modify (ASSAY_TYPE NULL);

--ORDER BY DATE--
--227
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','3H-ACT-066929ATube1',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('03-09-2003','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 227) * 2500) / 2500),3) from dual),2500,'C-Lab Biology H91.O3.K15','ZILTENP',TO_DATE('03/09/03', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 227;
--355
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-hUII',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('19-02-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 355) * 24) / 200),3) from dual),24,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('19/02/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 355;
--307
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'35S','35S-GTPgS',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('23-01-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 307) * 10) / 100),3) from dual),10,'C-Lab Biology H91.O3.K15','SIPPELV',TO_DATE('23/01/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 307 AND NUCLIDE_USAGE_ID = 627;
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'35S','35S-GTPgS',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('10-02-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 307) * 10) / 100),3) from dual),10,'C-Lab Biology H91.O3.K15','SIPPELV',TO_DATE('10/02/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 307 AND NUCLIDE_USAGE_ID = 699;
--588
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'35S','35S-GTPgS',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('05-11-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 588) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('05/11/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 588;
--587
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-NMU (rat) peak 2',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('05-11-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 587) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('05/11/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 587;
--525
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-NMU (rat), peak 2',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('07-10-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 525) * 130) / 200),3) from dual),130,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('07/10/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 525;
--557
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-NMU (rat) peak 1',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-10-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 557) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('12/10/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 557;
--556
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-NMU (rat), peak 1',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-10-2004','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 556) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('12/10/04', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 556;
--900
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-MIP-3beta',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('02-08-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 900) * 30) / 50),3) from dual),30,'C-Lab Biology H91.O3.K15','SINGERM',TO_DATE('02/08/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 900;
--583
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-078573 HCl',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-04-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 583) * 1.1) / 1000),3) from dual),1.1,'C-Lab Preclinic O4.K16','SEELANS',TO_DATE('08/04/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 583;
--534
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-078573',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-04-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 534) * 1.1) / 1000),3) from dual),1.1,'C-Lab Preclinic O4.K16','SEELANS',TO_DATE('08/04/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 534;
--362
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-078573E (HCl)',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-04-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 362) * 1.1) / 1000),3) from dual),1.1,'C-Lab Preclinic O4.K16','SEELANS',TO_DATE('08/04/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 362;
--1043
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-078573E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-12-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1043) * 7050) / 10000),3) from dual),7050,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('12/12/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1043;
--1051
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-078573E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('21-12-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1051) * 4000) / 4500),3) from dual),4000,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('21/12/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1051;
--683
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-NMU (rat) peak 1',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('01-02-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 683) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('01/02/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 683;
--648
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-Neuromedin',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('10-01-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 648) * 50) / 100),3) from dual),50,'C-Lab Biology H91.O3.K15','SIPPELV',TO_DATE('10/01/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 648;
--671
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('25-01-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 671) * 7200) / 11000),3) from dual),7200,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('25/01/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 671;
--672
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('25-01-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 672) * 4500) / 7500),3) from dual),4500,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('25/01/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 672;
--799
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-05-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 799) * 5751) / 24784),3) from dual),5751,'C-Lab Preclinic O4.K16','FLAESCS',TO_DATE('12/05/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 799 AND NUCLIDE_USAGE_ID = 2707;
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('29-11-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 799) * 473) / 24784),3) from dual),473,'C-Lab Preclinic O4.K16','FLAESCS',TO_DATE('29/11/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 799 AND NUCLIDE_USAGE_ID = 5961;
--782
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'33P','33P 2MeSADP',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('24-05-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 782) * 70) / 250),3) from dual),70,'C-Lab Biology H91.O4.K15.1','SINGERM',TO_DATE('24/05/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 782;
--979
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-077825K',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('04-10-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 979) * 5850) / 7000),3) from dual),5850,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('04/10/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 979;
--978
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-077825K',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('04-10-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 978) * 5000) / 5000),3) from dual),5000,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('04/10/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 978;
--1002
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-077825K',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('21-10-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1002) * 200) / 200),3) from dual),200,'C-Lab Preclinic O4.K16','MANGOLC',TO_DATE('21/10/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1002;
--963
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'33P','33P 2MeSADP',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('27-09-2005','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 963) * 6050) / 10000),3) from dual),6050,'C-Lab Biology H91.O4.K15.1','WEIGELA',TO_DATE('27/09/05', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 963;
--1055
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-128800C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('05-01-2006','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1055) * 4400) / 5000),3) from dual),4400,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('05/01/06', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1055;
--1065
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-128800C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-01-2006','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1065) * 7500) / 8000),3) from dual),7500,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('17/01/06', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1065;
--1114
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','125I-C3a (human)',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('10-05-2006','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1114) * 200) / 200),3) from dual),200,'C-Lab Biology H91.O3.K15','MANGOLC',TO_DATE('10/05/06', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1114;
--1118
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'125I','Active renin CIS Bio',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-05-2006','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1118) * 11000) / 11000),3) from dual),11000,'C-Lab Biology H91.O3.K15','REINJ',TO_DATE('12/05/06', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1118;
--1192
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','dihydronovobiocin',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-01-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1192) * 4000) / 4000),3) from dual),4000,'C-Lab Biology G12.O3.L00','BRUYERT',TO_DATE('08/01/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1192;
--1191
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','dihydronovobiocin',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-01-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1191) * 4000) / 4000),3) from dual),4000,'C-Lab Biology G12.O3.L00','BRUYERT',TO_DATE('08/01/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1191;
--1190
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','dihydronovobiocin',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-01-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1190) * 4000) / 4000),3) from dual),4000,'C-Lab Biology G12.O3.L00','BRUYERT',TO_DATE('08/01/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1190;
--1189
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','dihydronovobiocin',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-01-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1189) * 4000) / 4000),3) from dual),4000,'C-Lab Biology G12.O3.L00','BRUYERT',TO_DATE('08/01/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1189;
--1063
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-128800C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('11-07-2007','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1063) * 2000) / 50900),3) from dual),2000,'Storage DMPK H91.O4.K16.2','FLAESCS',TO_DATE('11/07/07', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1063;
--1653
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-178882D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-07-2008','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1653) * 6300) / 8000),3) from dual),6300,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('17/07/08', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1653;
--1655
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-178882D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('22-07-2008','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1655) * 7150) / 10000),3) from dual),7150,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('22/07/08', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1655;
--887
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-132577',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('16-06-2008','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 887) * 100) / 2000),3) from dual),100,'C-Lab Preclinic O4.K16','SEELANS',TO_DATE('16/06/08', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 887;
--862
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('16-06-2008','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 862) * 250) / 5000),3) from dual),250,'C-Lab Preclinic O4.K16','SEELANS',TO_DATE('16/06/08', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 862;
--1641
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-209905B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-06-2008','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1641) * 17350) / 20000),3) from dual),17350,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('17/06/08', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1641;
--1071
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('03-02-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1071) * 10000) / 9600000),3) from dual),10000,'C-Lab PPD H91.O4.K16.1','SEELANS',TO_DATE('03/02/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1071;
--1829
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','dog samples oral',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-02-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1829) * 13100) / 20000),3) from dual),13100,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('17/02/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1829;
--1910
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('04-05-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1910) * 220) / 220),3) from dual),220,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('04/05/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1910;
--1908
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('04-05-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1908) * 670) / 670),3) from dual),670,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('04/05/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1908;
--1909
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-280778C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('04-05-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1909) * 1330) / 1330),3) from dual),1330,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('04/05/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1909;
--1930
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-129968C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('26-05-2009','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 1930) * 15500) / 25000),3) from dual),15500,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('26/05/09', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 1930;
--2197
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','RO0470203-009-002 (Bosentan)',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('20-04-2010','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2197) * 2719) / 52939),3) from dual),2719,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('20/04/10', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2197;
--2184
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-064992B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('20-04-2010','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2184) * 18789) / 24000),3) from dual),18789,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('20/04/10', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2184;
--2195
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','ACT-080006A',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('21-04-2010','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2195) * 2748) / 53546),3) from dual),2748,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('21/04/10', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2195;
--2194
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','[14C] ACT-334441B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('21-04-2010','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2194) * 2719) / 52939),3) from dual),2719,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('21/04/10', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2194;
--2226
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','[14C] ACT-292706M',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('28-05-2010','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2226) * 13100) / 15000),3) from dual),13100,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('28/05/10', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2226;
--481
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-453859D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-08-2011','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 481) * 1502.6) / 4000),3) from dual),1502.6,'Storage DMPK H91.O4.K16.2','SELIMIA',TO_DATE('08/08/11', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 481;
--2525
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'3H','3H-Mibefradil',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('08-04-2011','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2525) * 20000) / 30000),3) from dual),20000,'C-Lab Preclinic O4.K16','WEIGELA',TO_DATE('08/04/11', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2525;
--2474
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','RO0470203-009-981 (Bosentan)',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('24-02-2011','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2474) * 11000) / 20000),3) from dual),11000,'C-Lab Biology H91.O3.K15','WEIGELA',TO_DATE('24/02/11', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2474;
--2179
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','TR19622',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-01-2011','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2179) * 10.69) / 369.4),3) from dual),10.69,'Storage DMPK H91.O4.K16.2','SCHAEUM',TO_DATE('17/01/11', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2179;
--2703
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-434964B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('15-11-2011','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 2703) * 20000) / 22500),3) from dual),20000,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('15/11/11', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 2703;
--3026
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-519276G',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('30-04-2013','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3026) * 9100) / 13000),3) from dual),9100,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('30/04/13', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3026;
--3031
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-519276G',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('07-05-2013','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3031) * 6900) / 13000),3) from dual),6900,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('07/05/13', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3031;
--3226
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-389949C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('13-05-2014','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3226) * 10649) / 12500),3) from dual),10649,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('13/05/14', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3226;
--3408
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-132577B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('18-08-2015','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3408) * 8430) / 10500),3) from dual),8430,'C-Lab PPD H91.O4.K16.1','WEIGELA',TO_DATE('18/08/15', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3408;
--3409
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-541468E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('19-08-2015','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3409) * 4591) / 5500),3) from dual),4591,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('19/08/15', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3409;
--3571
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-539313B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('15-11-2016','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3571) * 8200) / 10000),3) from dual),8200,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('15/11/16', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3571;
--3572
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-389949C',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('17-11-2016','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3572) * 9500) / 10500),3) from dual),9500,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('17/11/16', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3572;
--3661
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-541468E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('20-03-2017','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3661) * 10500) / 10500),3) from dual),10500,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('20/03/17', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3661;
--3662
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-539313B',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('22-03-2017','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3662) * 10500) / 10500),3) from dual),10500,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('22/03/17', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3662;
--3663
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-519276G',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('23-03-2017','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3663) * 10500) / 10500),3) from dual),10500,'Storage DMPK H91.O4.K16.2','WEIGELA',TO_DATE('23/03/17', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3663;
--3832
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1014-6470E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('13-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3832) * 9100) / 10000),3) from dual),9100,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('13/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3832;
--3830
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT541478D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('14-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3830) * 9500) / 10000),3) from dual),9500,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('14/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3830;
--3831
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1014-6470E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('15-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3831) * 7600) / 10000),3) from dual),7600,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('15/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3831;
--3836
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1014-6470E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('16-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3836) * 7800) / 10000),3) from dual),7800,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('16/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3836;
--3838
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT541478D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('19-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3838) * 8620) / 10000),3) from dual),8620,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('19/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3838;
--3844
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT541478D',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('21-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3844) * 9300) / 10000),3) from dual),9300,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('21/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3844;
--3845
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1014-6470E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('22-11-2018','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3845) * 8200) / 10000),3) from dual),8200,'Storage DMPK H91.O4.K16.2','JAOUENN',TO_DATE('22/11/18', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3845;
--3905
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1004-1239E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-11-2019','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3905) * 6900) / 9000),3) from dual),6900,'Storage DMPK H91.O4.K16.2','FABREFR1',TO_DATE('12/11/19', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3905;
--3904
INSERT INTO osiris.nuclide_bottle (nuclide_bottle_id,nuclide_name,substance_name,activity,volume,location,nuclide_user_id,activity_date,disposal_user_id,disposal_date,is_liquid,batch_name,tracer_type_id) VALUES (nuclide_bottle_seq_id.NEXTVAL,'14C','ACT-1004-1239E',(select TRUNC((((SELECT b.activity / exp(ln(2.0) *(trunc(TO_DATE('12-11-2019','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) FROM osiris.nuclide_bottle b, osiris.nuclide n WHERE b.nuclide_name = n.nuclide_name AND b.nuclide_bottle_id = 3904) * 7700) / 10000),3) from dual),7700,'Storage DMPK H91.O4.K16.2','FABREFR1',TO_DATE('12/11/19', 'DD/MM/YY'),NULL,NULL,'Y',NULL,4);
Update OSIRIS.NUCLIDE_USAGE SET NEW_NUCLIDE_BOTTLE_ID = (SELECT MAX(NUCLIDE_BOTTLE_ID) FROM OSIRIS.NUCLIDE_BOTTLE) WHERE DESTINATION IS NOT NULL AND NEW_NUCLIDE_BOTTLE_ID IS NULL AND NUCLIDE_BOTTLE_ID = 3904;

--update disposal route
update nuclide_disposal_route set disposal_route = 'Drain' where disposal_route = 'down the drain';
update nuclide_disposal_route set disposal_route = 'Waste basket' where disposal_route = 'into the waste basket';
update nuclide_disposal_route set disposal_route = 'Solvent waste' where disposal_route = 'with the solvent waste';
update nuclide_disposal_route set disposal_route = 'Animal disposal' where disposal_route = 'by animal disposal';
update nuclide_disposal_route set disposal_route = 'Valorec' where disposal_route = 'sent to Valorec';
update nuclide_disposal_route set disposal_route = 'EcoServe' where disposal_route = 'sent to EcoServe';

update nuclide_waste set disposal_route = 'Drain' where disposal_route = 'down the drain';
update nuclide_waste set disposal_route = 'Waste basket' where disposal_route = 'into the waste basket';
update nuclide_waste set disposal_route = 'Solvent waste' where disposal_route = 'with the solvent waste';
update nuclide_waste set disposal_route = 'Animal disposal' where disposal_route = 'by animal disposal';
update nuclide_waste set disposal_route = 'Valorec' where disposal_route = 'sent to Valorec';
update nuclide_waste set disposal_route = 'EcoServe' where disposal_route = 'sent to EcoServe';
update nuclide_waste set disposal_route = 'EcoServe' where disposal_route = 'sent to Ecoserve';

update nuclide_bottle set tracer_type_id = 3 where BATCH_NAME like 'In-Vivo-Sample%';

alter table nuclide_attached_aud modify (FILE_NAME null);
alter table nuclide_attached_aud modify (FILE_TYPE null);
alter table nuclide_attached_aud modify (FILE_PATH null);
alter table nuclide_attached_aud modify (FILE_FULLPATH null);
alter table nuclide_attached_aud modify (FILE_DATE null);

commit;
    
    
--SELECT
--    b.activity / exp(ln(2.0) *(trunc(TO_DATE('20-01-2019','DD-MM-YYYY')) - trunc(b.activity_date)) / n.half_time) as activity,
--    b.activity as initial_activity
--FROM
--    osiris.nuclide_bottle b,
--    osiris.nuclide n
--WHERE
--    b.nuclide_name = n.nuclide_name
--    AND b.nuclide_bottle_id = 3719;    
