package org.research.kadda.nuclide.entity;
// Generated May 12, 2022, 1:22:21 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * NuclideAllowance generated by hbm2java
 */
@Entity
@Table(name = "NUCLIDE_ALLOWANCE", schema = "OSIRIS")
@SequenceGenerator(name="NUCLIDE_ALLOWANCE_SEQ", sequenceName="OSIRIS.NUCLIDE_ALLOWANCE_ID_SEQ", allocationSize=1)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class NuclideAllowance implements java.io.Serializable {

	private static final long serialVersionUID = 4513484892817276305L;
	private int id;
	private Nuclide nuclide;
	private Double maxAmount;
	private Set<NuclideLocationAllowance> nuclideLocationAllowances = new HashSet<NuclideLocationAllowance>(0);

	public NuclideAllowance() {
	}

	public NuclideAllowance(int id) {
		this.id = id;
	}

	public NuclideAllowance(int id, Nuclide nuclide, Double maxAmount,
			Set<NuclideLocationAllowance> nuclideLocationAllowances) {
		this.id = id;
		this.nuclide = nuclide;
		this.maxAmount = maxAmount;
		this.nuclideLocationAllowances = nuclideLocationAllowances;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="NUCLIDE_ALLOWANCE_SEQ")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUCLIDE_NAME")
	public Nuclide getNuclide() {
		return this.nuclide;
	}

	public void setNuclide(Nuclide nuclide) {
		this.nuclide = nuclide;
	}

	@Column(name = "MAX_AMOUNT", precision = 126, scale = 0)
	public Double getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(Double maxAmount) {
		this.maxAmount = maxAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nuclideAllowance")
	@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public Set<NuclideLocationAllowance> getNuclideLocationAllowances() {
		return this.nuclideLocationAllowances;
	}

	public void setNuclideLocationAllowances(Set<NuclideLocationAllowance> nuclideLocationAllowances) {
		this.nuclideLocationAllowances = nuclideLocationAllowances;
	}

}
